### ISSUE TITLE
[Bug]: dataview-based task list occlusion

### ISSUE THREAD

**Issue by moltob** [chrisgrieser/shimmering-focus#304]
### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Check for updates).
- [X] I made sure that the issue is related to this theme by checking that the problem does *not* occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] The bug is about Obsidian desktop, Obsidian mobile is not supported by this theme.

### Bug Description

When using the dataview plugin with this theme, tasks lists are incorrectly aligned and partially occluded. Especially the checkbox itself is unreachable.

### Relevant Screenshot

This theme's rendering:

![image](https://github.com/chrisgrieser/shimmering-focus/assets/6240478/0426d5b2-33f8-4d47-9a1d-3933bcea27b9)

Default theme rendering:

![image](https://github.com/chrisgrieser/shimmering-focus/assets/6240478/918dc1dc-021b-446a-bf7e-41447b0c9164)

### To Reproduce

Install dataview plugin and create a task list, e.g. like this:

````markdown
```dataview
TASK
```
````

### Obsidian Version

1.5.12

### Installer Version

1.5.3

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [ ] Linux
- [X] Windows

**Comment by moltob** [comment]
Thanks a lot for your fast reply and help!

Tried your snippet and it perfectly fixed the issue. Visibility of the check box and text position is now completely identical between live preview (where it was broken) and reader mode (where it was always fine).

Feel free to close this issue whenever it fits your process.

Thanks again, that's impressive support!

**Comment by chrisgrieser** [comment]
In that case you might not even need the snippet – this is exactly the css that Shimmering Focus is using in its theme.css, with the update from this morning. After updating Shimmering Focus, try if it works without the snippet.

Only difference is the use of `!important`, which is override in case other plugins/snippets modify the behavior. So if it does not work without the snippet after updating, you likely have a plugin or snippet interfering. In this case you could try to figure out which one, or you could just use the snippet I provided here.

**Comment by maximilianigl** [comment]
I had the same problem, update didn't help, but the css fixed the issue.
Thank you!

**Comment by chrisgrieser** [comment]
@maximilianigl I still cannot reproduce the issue. If using the snippet fixes it, you also likely have a css snippet or plugin interfering.

**Comment by maximilianigl** [comment]
Apologies, I should have been clearer. It's almost certainly a plugin (of which I have too many). I tried for a bit narrowing it down and I excluded all the CSS snippets, but couldn't find the culprit. 
My comment wasn't meant as a "it's not fixed yet" - but more for ppl in the future facing the same issue. 
Also, thanks for the theme, it's fantastic :)!

**Comment by chrisgrieser** [comment]
Ah, I see, got it! Thank you for the kind words :)
